import { motion } from 'framer-motion';
import { ClipboardPaste, Settings, Rocket } from 'lucide-react';

const steps = [
  {
    num: '01',
    icon: ClipboardPaste,
    title: 'Paste your AI text',
    desc: 'Copy any text generated by ChatGPT, Gemini, Claude, DeepSeek, or any other AI tool into the editor.',
    color: '#7C5CFC',
  },
  {
    num: '02',
    icon: Settings,
    title: 'Choose your mode',
    desc: 'Select Standard for balanced results, Aggressive for maximum humanization, or Academic for scholarly writing.',
    color: '#A78BFA',
  },
  {
    num: '03',
    icon: Rocket,
    title: 'Copy & use instantly',
    desc: 'Get your humanized text in under 3 seconds. Copy it and use anywhere — essays, blogs, emails, reports.',
    color: '#60A5FA',
  },
];

export default function HowItWorks() {
  return (
    <section id="how" className="relative z-10 px-4 sm:px-6 py-24">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="inline-block text-xs font-semibold text-[#A78BFA] uppercase tracking-[0.15em] mb-3">
            Process
          </span>
          <h2 className="font-[Space_Grotesk] text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
            Three steps to <span className="gradient-text">human-sounding</span> text
          </h2>
        </motion.div>

        <div className="grid md:grid-cols-3 gap-6">
          {steps.map((step, i) => (
            <motion.div
              key={step.num}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-50px' }}
              transition={{ duration: 0.6, delay: i * 0.15 }}
              className="spotlight-card group relative bg-[#111120] border border-white/[0.06] rounded-2xl p-8 card-lift"
              onMouseMove={(e) => {
                const rect = e.currentTarget.getBoundingClientRect();
                e.currentTarget.style.setProperty('--mouse-x', `${e.clientX - rect.left}px`);
                e.currentTarget.style.setProperty('--mouse-y', `${e.clientY - rect.top}px`);
              }}
            >
              {/* Connector line */}
              {i < steps.length - 1 && (
                <div className="hidden md:block absolute top-12 -right-3 w-6 h-px bg-gradient-to-r from-[#7C5CFC]/30 to-transparent z-10" />
              )}

              <div className="flex items-center justify-between mb-6">
                <span
                  className="font-[Space_Grotesk] text-5xl font-bold opacity-10 group-hover:opacity-20 transition-opacity"
                  style={{ color: step.color }}
                >
                  {step.num}
                </span>
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center transition-transform duration-300 group-hover:scale-110"
                  style={{ background: `${step.color}15` }}
                >
                  <step.icon className="w-5 h-5" style={{ color: step.color }} />
                </div>
              </div>

              <h3 className="text-lg font-semibold text-[#F0EEF9] mb-3">{step.title}</h3>
              <p className="text-sm text-[#9B97B8] leading-relaxed">{step.desc}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
